enum MouseId
{
	APP_TOUCH_MOUSEID = SDL_TOUCH_MOUSEID
};

enum MouseButton
{
	APP_BUTTON_LEFT   = SDL_BUTTON_LEFT,
	APP_BUTTON_MIDDLE = SDL_BUTTON_MIDDLE,
	APP_BUTTON_RIGHT  = SDL_BUTTON_RIGHT,
	APP_BUTTON_X1     = SDL_BUTTON_X1,
	APP_BUTTON_X2     = SDL_BUTTON_X2
};

enum MouseButtonMask
{
	APP_BUTTON_LMASK  = SDL_BUTTON_LMASK,
	APP_BUTTON_MMASK  = SDL_BUTTON_MMASK,
	APP_BUTTON_RMASK  = SDL_BUTTON_RMASK,
	APP_BUTTON_X1MASK = SDL_BUTTON_X1MASK,
	APP_BUTTON_X2MASK = SDL_BUTTON_X2MASK
};

enum MouseWheelDirection
{
	APP_MOUSEWHEEL_NORMAL  = SDL_MOUSEWHEEL_NORMAL,
	APP_MOUSEWHEEL_FLIPPED = SDL_MOUSEWHEEL_FLIPPED
};